### ISSUE TITLE
argo-cd-action/v1.17.0 gets stuck indefinitely at App Sync stage

### ISSUE THREAD

**Issue by neeraj-yadav-mck** [clowdhaus/argo-cd-action#21]
**Describe the bug**
Using argo-cd-action/v1.15.0, argo-cd-action/v1.17.0, ArgoCD workflow gets stuck at App Sync stage indefinitely.
ArgoCD server version: v2.5.1+504da42

**To Reproduce**
- name: Argocd app sync
        uses: clowdhaus/argo-cd-action/@v1.17.0
        with:
          version: 2.5.1
          command: app sync ${{ env.PARENT_APP_NAME }} -l argocd.argoproj.io/instance=${{ env.PARENT_APP_NAME }}
          options: --auth-token=${{ secrets.ARGOCD_AUTH_TOKEN }} --server ${{ env.ARGOCD_SERVER }}

**Comment by michalziobro** [comment]
I had a similar issue, although with different command. In my case the solution was to add `--grpc-web` flag

**Comment by bryantbiggs** [comment]
I don't think this is related to the action but instead related to the use of the CLI. closing for now unless there are further details that point back to the action itself; happy to take a look if there is
