### ISSUE TITLE
Fails to find argocd on subsequent runs

### ISSUE THREAD

**Issue by cenobitedk** [clowdhaus/argo-cd-action#8]
**Describe the bug**
When I first introduced this action it worked fine. However on subsequent runs it fails. I'm using a self-hosted runner without a specific clean-up step.

**To Reproduce**
1. Create a workflow with this action
2. Run it and see it works
3. Run it again and it will fail with
```sh
Unexpected error attempting to determine if executable file exists '/home/github/_work/_tool/argocd/2.0.0/x64/argocd/argocd': Error: ENOTDIR: not a directory, stat '/home/github/_work/_tool/argocd/2.0.0/x64/argocd/argocd'
Error: Unable to locate executable file: argocd. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
```

**Expected behavior**
I expected the action to be succesful every time.

**Additional context**
The `argocd` file is located `/home/github/_work/_tool/argocd/2.0.0/x64/argocd`, so the mechanism to find already downloaded executable is searching with a path that is too long.

**Comment by cenobitedk** [comment]
@bryantbiggs Do you have time to look at this bug?

**Comment by bryantbiggs** [comment]
my apologies @cenobitedk , let me see if I can find some time to revisit this in the next few days

**Comment by cenobitedk** [comment]
Thank you Bryant!
